### ISSUE TITLE
Is it possible to set different speeds or totalsensitivity for each design program?

### ISSUE THREAD

**Issue by starletzzang** [AndunHH/spacemouse#56]
Is it possible to set different speeds or totalsensitivity for each design program?
For example, in Creo is needed for proper speed,
but in fusion360, it is too slow.

I tried setting the speed in the 3dconnextion setting window, but it doesn't seem to be applied.

thanks you.

**Comment by AndunHH** [comment]
Unfortunately, this can't be configured in the space mouse. The mouse doesn't know, which programm your using on the PC.

This is also related to #13, where we discussed this already, because the driver somehow doesn't work perfectly with our emulated mouse in this regard...

Therefore I'm closing this issue, as we have already #13.
